# Define the access token that will be used to authenticate with the secrets manager
accessToken: {}
  # # Name of the token.
  # # Required
  # name: gitlab-secrets
  # # Labes to attach to the secret
  # # Optional
  # labels:
  #   type: gitlab
  # # The token used for authentication.
  # # Required
  # token: "my-access-token"

secretStore:
  name: vault-backend
  provider: gitlab
  url: www.example.com
  accessToken:
    name: token-name
    key: my-key
  projectID: projectid
  groupIDs:
    - 12345
    - 67890
  environment: environment
  conditions:
    - namespaces:
        - external-secrets
        - default
  caProvider:
    key: ca-bundle
    name: name
    namespace: namespace
    type: Secret
  # name: vault-backend
  # spec:
  #   provider:
  #     vault:
  #       server: "http://my.vault.server:8200"
  #       path: "secret"
  #       version: "v2"
  #       auth:
  #         tokenSecretRef:
  #           name: "vault-token"
  #           key: "token"

clusterSecretStore: {}
  # name: vault-backend
  # spec:
  #   provider:
  #     vault:
  #       server: "http://my.vault.server:8200"
  #       path: "secret"
  #       version: "v2"
  #       auth:
  #         tokenSecretRef:
  #           name: "vault-token"
  #           key: "token"

# Define an External Secret resource
externalSecret: {}
  # # Name of the External Secret
  # # Required
  # name: external-secret
  # # Time between syncs
  # # Optional. Defaults to 60 seconds
  # refreshInterval: "15s"
  # # Labels to attach to the External Secret
  # # Optional
  # labels:
  #   type: external-secret
  # # Secret Store or Cluster Secret Store that will hold the desired secret
  # # Required
  # secretStore:
  #   # Name of the Secret Store or Cluster Secret Store
  #   name: vault-backend
  #   # Kind of Secret Store
  #   # ClusterSecretStore or SecretStore
  #   kind: SecretStore
  # # Define the resulting secret
  # targetSecret:
  #   # Name of the desired secret
  #   name: example-sync
  #   # Define the creation policy of the secret
  #   # Defaults to Owner
  #   # Owner, Orphan, Merge, None
  #   policy: Owner
  #   # Define that data that will make the secret
  #   # At least one entry is required
  #   # Multiple entries allowed
  #   data:
  #     # Name of the key that will be in the secret
  #     # Required
  #   - secretKey: foobar
  #     # Where to pull the secret from
  #     # Required
  #     remoteRef:
  #       # The key that holds the value in the secret store
  #       # Required
  #       key: foo
  #       # If the key has multiple properties specify the specific property
  #       # Optional
  #       # Needed if using OpenBao or HashiCorp Vault
  #       property: my-value
  #   - secretKey: toobar
  #     remoteRef:
  #       key: bar
  #       property: their-value
