clusterSecretStores: {}
  # global:
  #   caProvider:
  #     type: Secret
  #     name: vault-ca
  #     key: ca.crt
  #     namespace: external-secrets

  # main1:
  #   provider:
  #     gitlab:
  #       url: https://gitlab.example.com
  #       auth:
  #         SecretRef:
  #           accessToken:
  #             name: access
  #             key: token
  #             namespace: default
  #       projectID: "12345"
  #       inheritFromGroups: false

  # main2:
  #   provider:
  #     vault:
  #       server: https://vault-b.example.com
  #       path: secret
  #       version: "v2"
  #       auth:
  #         kubernetes:
  #           mountPath: kubernetes
  #           role: eso
  #           serviceAccountRef:
  #             name: external-secrets
  #             namespace: external-secrets
